# Generated by Django 5.0.2 on 2024-10-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Redikt',
            new_name='Member',
        ),
    ]
