# Generated by Django 5.0.2 on 2024-10-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('discription_uz', models.TextField(blank=True, null=True)),
                ('discription_ru', models.TextField(blank=True, null=True)),
                ('discription_en', models.TextField(blank=True, null=True)),
                ('thumb', models.ImageField(upload_to='news/')),
            ],
        ),
    ]
