# Generated by Django 5.0.2 on 2024-10-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_text_history_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='best',
        ),
        migrations.RemoveField(
            model_name='product',
            name='doi',
        ),
    ]
